spring:
  sql: 
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-delicate-bonus-a253bz20.eu-central-1.pg.koyeb.app/koyebdb?user=koyeb-adm&password=cb9FvZkGp7EL
    username: koyeb-adm
    password: cb9FvZkGp7EL
    
#MyBatis settings
mybatis:
  #config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:**/mapper/*/*.xml