spring:
  sql: 
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    
#MyBatis settings
mybatis:
  #config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:**/mapper/*/*.xml